# Generated by Django 4.2 on 2025-12-08 20:13

from django.db import migrations, models, connection


def add_fields_if_not_exists(apps, schema_editor):
    """Add fields only if they don't already exist in the database."""
    db_table = "core_userprofile"
    db_engine = connection.vendor

    with connection.cursor() as cursor:
        is_premium_exists = False
        subscription_status_exists = False

        if db_engine == "mysql":
            # MySQL-specific check
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'is_premium'
            """,
                [db_table],
            )
            is_premium_exists = cursor.fetchone()[0] > 0

            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'subscription_status'
            """,
                [db_table],
            )
            subscription_status_exists = cursor.fetchone()[0] > 0
        elif db_engine == "sqlite":
            # SQLite-specific check - use PRAGMA table_info
            cursor.execute(f"PRAGMA table_info({db_table})")
            columns = [row[1] for row in cursor.fetchall()]
            is_premium_exists = "is_premium" in columns
            subscription_status_exists = "subscription_status" in columns

        # Add is_premium if it doesn't exist
        if not is_premium_exists:
            if db_engine == "mysql":
                cursor.execute(
                    f"ALTER TABLE `{db_table}` ADD COLUMN `is_premium` TINYINT(1) NOT NULL DEFAULT 0"
                )
            elif db_engine == "sqlite":
                cursor.execute(
                    f"ALTER TABLE {db_table} ADD COLUMN is_premium INTEGER NOT NULL DEFAULT 0"
                )

        # Add subscription_status if it doesn't exist
        if not subscription_status_exists:
            if db_engine == "mysql":
                cursor.execute(
                    f"ALTER TABLE `{db_table}` ADD COLUMN `subscription_status` VARCHAR(50) NOT NULL DEFAULT 'inactive'"
                )
            elif db_engine == "sqlite":
                cursor.execute(
                    f"ALTER TABLE {db_table} ADD COLUMN subscription_status VARCHAR(50) NOT NULL DEFAULT 'inactive'"
                )


def reverse_add_fields(apps, schema_editor):
    """Reverse operation - remove fields if they exist."""
    db_table = "core_userprofile"
    db_engine = connection.vendor

    with connection.cursor() as cursor:
        if db_engine == "mysql":
            # Check if columns exist and remove them
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'is_premium'
            """,
                [db_table],
            )
            if cursor.fetchone()[0] > 0:
                cursor.execute(f"ALTER TABLE `{db_table}` DROP COLUMN `is_premium`")

            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'subscription_status'
            """,
                [db_table],
            )
            if cursor.fetchone()[0] > 0:
                cursor.execute(f"ALTER TABLE `{db_table}` DROP COLUMN `subscription_status`")
        elif db_engine == "sqlite":
            # SQLite doesn't support DROP COLUMN easily, skip in reverse
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_fields_if_not_exists, reverse_add_fields),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="userprofile",
                    name="is_premium",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="userprofile",
                    name="subscription_status",
                    field=models.CharField(
                        default="inactive",
                        help_text="Tracks the latest status returned by Stripe for this user's checkout session.",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
