# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_hearts_userprofile_hearts_last_refill_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sound_enabled",
            field=models.BooleanField(
                default=True, help_text="Allow lesson/exercise audio feedback."
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="animations_enabled",
            field=models.BooleanField(
                default=True, help_text="Allow celebratory and mascot animations."
            ),
        ),
    ]
