# Generated by Django 4.2.27 on 2026-01-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_dailyusage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailyusage",
            new_name="core_dailyu_user_id_71a49e_idx",
            old_name="core_dailyusage_user_feature_date_idx",
        ),
    ]
