# Generated by Django 4.2.27 on 2026-01-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_hearts_userprofile_hearts_last_refill_at"),
    ]

    operations = []
