# Generated by Django 4.2 on 2026-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_reminder_daily_to_weekly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email_reminder_preference",
            field=models.CharField(
                choices=[("none", "No Reminders"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                default="none",
                max_length=10,
            ),
        ),
    ]
