# Generated by Django 4.2.30 on 2026-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_periodic_tasks_streak_missions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signup_platform",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
