# Generated by Django 4.2.30 on 2026-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_userprofile_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
