# Generated by Django 4.2.30 on 2026-07-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_userprofile_timezone_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_completed_date', 'streak'], name='userprofile_streak_idx'),
        ),
    ]
