# Generated by Django 5.2.17 on 2026-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_userprofile_streak_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signup_attribution",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
