# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial_idempotency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationidempotency",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Notification idempotencies",
            },
        ),
    ]
