# Generated by Django 4.2.30 on 2026-07-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationidempotency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=200)),
                ('purpose', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Delivered'), ('error', 'Error'), ('expired', 'Expired before check')], db_index=True, default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_push_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
