export const ANALYTICS_EVENTS = [
  "pricing_view",
  "checkout_created",
  "checkout_completed",
  "entitlement_lookup",
  "webhook_received",
  "dashboard_view",
  "cta_click",
  "upgrade_click",
  "weak_skill_click",
  "sort_change",
  "filter_change",
  "improve_recommendation_click",
  "quick_card_exercises_click",
  "exercise_skill_intent_received",
  "exercise_skill_intent_mapped",
  "exercise_skill_intent_unmapped",
  "exercise_skill_intent_cleared",
  "exercise_skill_intent_manual_category",
  "exercise_skill_intent_engaged",
  "exercise_skill_intent_mapped_zero",
  "exercises_page_view",
  "exercise_started",
  "questionnaire_step_view",
  "questionnaire_answer_submitted",
  "questionnaire_abandoned",
  "questionnaire_completed",
] as const;

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[number];
