/**
 * @garzoni/tokens — the single source of truth for layout tokens
 * (spacing, radius, typography, shadows) across web, mobile and email.
 *
 * Colours are NOT here yet; they still live in `brand/kit/tokens.css` and its
 * mirrors. This package owns the layout scale only.
 *
 * Consumers:
 *  - mobile: `mobile/src/theme/tokens.ts` re-exports this module verbatim.
 *  - web:    `packages/tokens/dist/tokens.css` (generated by `pnpm -F
 *            @garzoni/tokens build:css`) is imported from `frontend/src/index.css`,
 *            and `frontend/tailwind.config.cjs` reads the semantic aliases.
 *
 * If you change a value here, run `pnpm -F @garzoni/tokens build:css` and commit
 * the regenerated CSS. See docs/dev/spacing-contract.md.
 */

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  xxxxl: 48,
} as const;

export const radius = {
  sm: 6,
  md: 10,
  lg: 14,
  xl: 20,
  /** Canonical card radius across web + mobile + email. */
  card: 20,
  full: 9999,
} as const;

export const typography = {
  xs: 11,
  sm: 13,
  base: 15,
  md: 16,
  lg: 18,
  xl: 22,
  xxl: 28,
  hero: 34,
} as const;

/**
 * Semantic layout constants derived from the scale above. Reach for these
 * rather than picking a raw `spacing.*` step, so the app-wide gutter and
 * rhythm can be tuned in one place.
 */
export const layout = {
  /** Base horizontal inset for a screen/page. */
  screenPaddingX: spacing.xl,
  /** Gap between related items in a vertical stack. */
  stackGap: spacing.lg,
  /** Gap between distinct page sections. */
  sectionGap: spacing.xxxl,
  /** Default card interior padding (`padding="md"`). */
  cardPadding: spacing.xl,
  /** Compact card interior padding (`padding="sm"`). */
  cardPaddingSm: spacing.lg,
  /** Roomy card interior padding (`padding="lg"`). */
  cardPaddingLg: spacing.xxl,
} as const;

/** React Native shadow presets. Web uses Tailwind's shadow utilities instead. */
export const shadows = {
  sm: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  lg: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 5,
  },
} as const;

export type Spacing = typeof spacing;
export type Radius = typeof radius;
export type Typography = typeof typography;
export type Layout = typeof layout;
