# Generated by Django 4.2.30 on 2026-05-13 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgeting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="budgetenvelope",
            name="uniq_user_category_envelope",
        ),
        migrations.RemoveConstraint(
            model_name="budgetperiodsummary",
            name="uniq_user_period_start",
        ),
        migrations.RemoveConstraint(
            model_name="linkedaccount",
            name="uniq_user_provider_account",
        ),
        migrations.RenameIndex(
            model_name="linkedaccount",
            new_name="budgeting_l_user_id_193a12_idx",
            old_name="budget_la_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="linkedaccount",
            new_name="budgeting_l_provide_a9b827_idx",
            old_name="budget_la_prov_status_idx",
        ),
        migrations.RenameIndex(
            model_name="providerwebhookevent",
            new_name="budgeting_p_provide_b523db_idx",
            old_name="budget_pwh_prov_proc_idx",
        ),
        migrations.RenameIndex(
            model_name="spendinganomaly",
            new_name="budgeting_s_user_id_7ac1b5_idx",
            old_name="budget_anom_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="spendinganomaly",
            new_name="budgeting_s_user_id_c5e1e0_idx",
            old_name="budget_anom_user_res_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="budgeting_t_user_id_db31b1_idx",
            old_name="budget_tx_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="budgeting_t_user_id_414415_idx",
            old_name="budget_tx_user_cat_date_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="budgeting_t_provide_a6f7ce_idx",
            old_name="budget_tx_provid_idx",
        ),
        migrations.AlterUniqueTogether(
            name="budgetenvelope",
            unique_together={("user", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="budgetperiodsummary",
            unique_together={("user", "period_start")},
        ),
        migrations.AlterUniqueTogether(
            name="linkedaccount",
            unique_together={("user", "provider", "provider_account_id")},
        ),
    ]
