# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0002_remove_budgetenvelope_uniq_user_category_envelope_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetperiodsummary",
            options={
                "ordering": ["-period_start"],
                "verbose_name_plural": "Budget period summaries",
            },
        ),
        migrations.AlterModelOptions(
            name="spendinganomaly",
            options={"ordering": ["-detected_for"], "verbose_name_plural": "Spending anomalies"},
        ),
        migrations.AlterModelOptions(
            name="transactioncategory",
            options={"ordering": ["label"], "verbose_name_plural": "Transaction categories"},
        ),
    ]
