# Generated by Django 4.2.30 on 2026-08-02 21:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0003_alter_budgetperiodsummary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=128)),
                ('dialect_slug', models.CharField(default='generic', max_length=32)),
                ('dialect_label', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='', max_length=8)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('was_trial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reverted', 'Reverted')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgeting.statementimport'),
        ),
        migrations.AddIndex(
            model_name='statementimport',
            index=models.Index(fields=['user', '-created_at'], name='budgeting_s_user_id_48a820_idx'),
        ),
    ]
