# Generated by Django 5.2.16 on 2026-08-18 22:04

import budgeting.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_decode_statement_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedaccount',
            name='encrypted_access_token',
            field=budgeting.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='encrypted_refresh_token',
            field=budgeting.fields.EncryptedTextField(blank=True),
        ),
    ]
