# Generated by Django 4.2.27 on 2026-01-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_goal_purchase_constraints"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="funnelevent",
            new_name="finance_fun_created_14f85e_idx",
            old_name="funnelevent_created_idx",
        ),
    ]
