# Generated by Django 4.2.27 on 2026-01-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_rename_funnelevent_created_idx_finance_fun_created_14f85e_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="financialgoal",
            name="uniq_user_goal_name",
        ),
        migrations.RemoveConstraint(
            model_name="userpurchase",
            name="uniq_user_reward_purchase",
        ),
        migrations.RemoveIndex(
            model_name="funnelevent",
            name="finance_fun_created_14f85e_idx",
        ),
    ]
