# Generated by Django 4.2 on 2026-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_portfolio_asset_types_and_symbol_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioentry",
            name="is_paper_trade",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="simulatedsavingsaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
