# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_funnelevent_platform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfactprogress",
            options={"verbose_name_plural": "User fact progress"},
        ),
    ]
