# Generated by Django 4.2 on 2026-01-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(help_text="Version number", unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this version is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "questionnaire_structure",
                    models.JSONField(
                        help_text="Complete questionnaire structure with questions, sections, and skip logic"
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_questionnaireversion",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("current_section_index", models.PositiveIntegerField(default=0)),
                ("current_question_index", models.PositiveIntegerField(default=0)),
                (
                    "answers",
                    models.JSONField(default=dict, help_text="Stored answers keyed by question_id"),
                ),
                (
                    "section_answers",
                    models.JSONField(
                        default=dict, help_text="Answers organized by section for summary display"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rewards_granted",
                    models.BooleanField(
                        default=False, help_text="Whether rewards have been granted for completion"
                    ),
                ),
                (
                    "completion_idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Idempotency key to prevent duplicate reward grants",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "time_spent_per_question",
                    models.JSONField(
                        default=dict, help_text="Time spent (in seconds) per question_id"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        help_text="Questionnaire version this progress is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_entries",
                        to="onboarding.questionnaireversion",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_questionnaireprogress",
            },
        ),
        migrations.AddIndex(
            model_name="questionnaireprogress",
            index=models.Index(fields=["user", "status"], name="onboarding__user_id_5fea05_idx"),
        ),
        migrations.AddIndex(
            model_name="questionnaireprogress",
            index=models.Index(fields=["updated_at"], name="onboarding__updated_ae76cb_idx"),
        ),
    ]
