# Generated by Django 4.2.30 on 2026-06-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_shorten_questionnaire"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaireprogress",
            options={"verbose_name_plural": "Questionnaire progress"},
        ),
    ]
