# Generated by Django 4.2.27 on 2026-01-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0007_mastery_user_due_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mastery",
            new_name="core_master_user_id_45d145_idx",
            old_name="mastery_user_due_idx",
        ),
    ]
