# Generated by Django 4.2.27 on 2026-01-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0008_rename_mastery_user_due_idx_core_master_user_id_45d145_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mastery",
            name="core_master_user_id_45d145_idx",
        ),
    ]
