# Generated by Django 4.2 on 2026-02-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0010_ensure_exercise_version_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonsection",
            name="exercise_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("drag-and-drop", "Drag and Drop"),
                    ("multiple-choice", "Multiple Choice"),
                    ("numeric", "Numeric"),
                    ("budget-allocation", "Budget Allocation"),
                    ("fill-in-table", "Fill In Table"),
                    ("scenario-simulation", "Scenario Simulation"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
