# Generated by Django 4.2 on 2026-02-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0014_add_translation_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="path",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Path",
                "verbose_name_plural": "Paths",
            },
        ),
    ]
