# Generated by Django 4.2.30 on 2026-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0025_rename_userprogress_streak_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="learning_session_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Consecutive days of activity on this course (not the global streak).",
            ),
        ),
    ]
