# Generated by Django 4.2.30 on 2026-05-19 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0037_lesson_slug_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
                ("proficiency", models.PositiveIntegerField(default=0)),
                ("recorded_on", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "core_masterysnapshot",
                "indexes": [
                    models.Index(
                        fields=["user", "skill", "recorded_on"], name="snap_user_skill_date_idx"
                    )
                ],
                "unique_together": {("user", "skill", "recorded_on")},
            },
        ),
    ]
