# Generated by Django 4.2.30 on 2026-06-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0042_userprogress_unique_user_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="learning_session_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Per-course consecutive-day streak (NOT total sessions and NOT the global profile streak). Bumps once per day the learner is active on this course; resets to 1 after a gap. See Profile.streak for the global streak.",
            ),
        ),
    ]
