# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0043_alter_userprogress_learning_session_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userexerciseprogress",
            options={"verbose_name_plural": "User exercise progress"},
        ),
    ]
