# Generated by Django 4.2.30 on 2026-06-29 20:55

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0044_alter_userexerciseprogress_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("comparison", "Comparison"),
                            ("answer", "Answer / FAQ"),
                        ],
                        db_index=True,
                        default="guide",
                        max_length=20,
                    ),
                ),
                ("meta_description", models.TextField(blank=True)),
                ("excerpt", models.TextField(blank=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                ("author", models.CharField(default="Garzoni Team", max_length=120)),
                ("image", models.ImageField(blank=True, null=True, upload_to="article_images/")),
                ("faq", models.JSONField(blank=True, null=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_lessons",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="education.lesson"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "education_article",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="education_a_is_publ_e3ce30_idx",
                    )
                ],
            },
        ),
    ]
