# Generated by Django 4.2 on 2026-02-15 22:48
# Alter table names to final core_* only if the tables exist (support tables may be missing on fresh SQLite).

from django.db import migrations


def alter_tables_if_exist(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        with schema_editor.connection.cursor() as c:
            c.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='support_supportentry'"
            )
            if c.fetchone():
                schema_editor.execute(
                    "ALTER TABLE support_supportentry RENAME TO core_supportentry"
                )
            c.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='support_supportfeedback'"
            )
            if c.fetchone():
                schema_editor.execute(
                    "ALTER TABLE support_supportfeedback RENAME TO core_supportfeedback"
                )
    elif vendor == "postgresql":
        schema_editor.execute(
            """
            DO $$ BEGIN
                IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = current_schema() AND tablename = 'support_supportentry') THEN
                    ALTER TABLE support_supportentry RENAME TO core_supportentry;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = current_schema() AND tablename = 'support_supportfeedback') THEN
                    ALTER TABLE support_supportfeedback RENAME TO core_supportfeedback;
                END IF;
            END $$;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_rename_faq_to_support"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(name="supportentry", table="core_supportentry"),
                migrations.AlterModelTable(name="supportfeedback", table="core_supportfeedback"),
            ],
            database_operations=[
                migrations.RunPython(alter_tables_if_exist, migrations.RunPython.noop),
            ],
        ),
    ]
