# Generated by Django 4.2.30 on 2026-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="source",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("exercise_hint", "Exercise Hint"),
                    ("exercise_explain", "Exercise Explain"),
                    ("voice", "Voice"),
                    ("coach_brief", "Coach Brief"),
                    ("cfo_coach", "CFO Coach"),
                    ("cfo_coach_archived", "CFO Coach (Archived)"),
                ],
                default="chat",
                max_length=32,
            ),
        ),
    ]
