# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_alter_conversation_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportentry",
            options={"verbose_name_plural": "Support entries"},
        ),
        migrations.AlterModelOptions(
            name="supportfeedback",
            options={"verbose_name_plural": "Support feedback"},
        ),
    ]
