# Generated by Django 4.2.30 on 2026-06-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0008_alter_supportentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppReviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("unhappy", "Unhappy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("message", models.TextField(blank=True, default="")),
                ("routed_to_store", models.BooleanField(default=False)),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                ("app_version", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_appreviewresponse",
                "indexes": [
                    models.Index(
                        fields=["sentiment", "-created_at"], name="core_apprev_sentime_9898a7_idx"
                    )
                ],
            },
        ),
    ]
