# Generated by Django 4.2.27 on 2026-01-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0003_mission_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="missioncompletion",
            new_name="core_missio_user_id_cac5aa_idx",
            old_name="missioncomp_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="missioncompletion",
            new_name="core_missio_user_id_9ff738_idx",
            old_name="missioncomp_user_mstat_idx",
        ),
        migrations.RenameIndex(
            model_name="missioncompletion",
            new_name="core_missio_complet_7f2238_idx",
            old_name="missioncomp_completed_idx",
        ),
        migrations.RenameIndex(
            model_name="missionperformance",
            new_name="core_missio_user_id_d17a21_idx",
            old_name="missionperf_user_created_idx",
        ),
    ]
