# Generated by Django 4.2.27 on 2026-01-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamification",
            "0004_rename_missioncomp_user_status_idx_core_missio_user_id_cac5aa_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="missioncompletion",
            name="core_missio_user_id_cac5aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="missioncompletion",
            name="core_missio_user_id_9ff738_idx",
        ),
        migrations.RemoveIndex(
            model_name="missioncompletion",
            name="core_missio_complet_7f2238_idx",
        ),
        migrations.RemoveIndex(
            model_name="missionperformance",
            name="core_missio_user_id_d17a21_idx",
        ),
    ]
