# Generated by Django 4.2.30 on 2026-06-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0011_duel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="multistepmissionprogress",
            options={"verbose_name_plural": "Multi-step mission progress"},
        ),
    ]
