# Generated by Django 4.2.30 on 2026-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0013_seed_investor_quests'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rewardledgerentry',
            index=models.Index(fields=['user', '-created_at'], name='reward_ledger_usr_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardledgerentry',
            index=models.Index(fields=['created_at'], name='reward_ledger_created_idx'),
        ),
    ]
