# Generated by Django 4.2.30 on 2026-07-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0014_rewardledger_time_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakWager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_points', models.IntegerField()),
                ('reward_points', models.IntegerField()),
                ('reward_coins', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_days', models.IntegerField(default=7)),
                ('streak_at_start', models.IntegerField()),
                ('started_on', models.DateField()),
                ('deadline_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_wagers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_streakwager',
                'indexes': [models.Index(fields=['status', 'deadline_on'], name='streakwager_status_dl_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='streakwager',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='streakwager_one_active_per_user'),
        ),
    ]
