# Generated by Django 4.2.30 on 2026-07-25 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0016_periodic_task_resolve_wagers'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=10)),
                ('cycle_id', models.CharField(db_index=True, max_length=40)),
                ('index', models.IntegerField(default=0, help_text='Which cohort within the tier/cycle (0-based).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_league',
            },
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(db_index=True, max_length=40)),
                ('weekly_xp', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('promoted', 'Promoted'), ('held', 'Held'), ('demoted', 'Demoted')], max_length=10, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gamification.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_leaguemember',
            },
        ),
        migrations.AddIndex(
            model_name='league',
            index=models.Index(fields=['cycle_id', 'tier'], name='league_cycle_tier_idx'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('tier', 'cycle_id', 'index'), name='league_tier_cycle_index_uniq'),
        ),
        migrations.AddIndex(
            model_name='leaguemember',
            index=models.Index(fields=['league', '-weekly_xp'], name='leaguemember_standings_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaguemember',
            constraint=models.UniqueConstraint(fields=('league', 'user'), name='leaguemember_league_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='leaguemember',
            constraint=models.UniqueConstraint(fields=('user', 'cycle_id'), name='leaguemember_user_cycle_uniq'),
        ),
    ]
